// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ostawy.Data;

#nullable disable

namespace Ostawy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608131451_AddInDriveBiddingSystem")]
    partial class AddInDriveBiddingSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ostawy.Models.JobBid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobRequestId")
                        .HasColumnType("int");

                    b.Property<decimal>("OfferPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobBids");
                });

            modelBuilder.Entity("Ostawy.Models.JobRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CustomerPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobRequests");
                });

            modelBuilder.Entity("Ostawy.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ostawy.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "plumbing",
                            Email = "ahmed@ostawy.com",
                            FullName = "أحمد محمد",
                            IsAvailable = true,
                            Lat = 30.0444,
                            Lng = 31.235700000000001,
                            PasswordHash = "123456",
                            Price = 80m,
                            Rating = 4.9000000000000004,
                            ReviewsCount = 128,
                            Role = "worker",
                            Specialty = "سباكة"
                        },
                        new
                        {
                            Id = 2,
                            Category = "electric",
                            Email = "mahmoud@ostawy.com",
                            FullName = "محمود خالد",
                            IsAvailable = true,
                            Lat = 30.059999999999999,
                            Lng = 31.260000000000002,
                            PasswordHash = "123456",
                            Price = 100m,
                            Rating = 4.7999999999999998,
                            ReviewsCount = 97,
                            Role = "worker",
                            Specialty = "كهرباء"
                        },
                        new
                        {
                            Id = 3,
                            Category = "ac",
                            Email = "samer@ostawy.com",
                            FullName = "سامر علي",
                            IsAvailable = true,
                            Lat = 30.035,
                            Lng = 31.219999999999999,
                            PasswordHash = "123456",
                            Price = 150m,
                            Rating = 4.7000000000000002,
                            ReviewsCount = 64,
                            Role = "worker",
                            Specialty = "تكييف وتبريد"
                        },
                        new
                        {
                            Id = 4,
                            Category = "paint",
                            Email = "youssef_h@ostawy.com",
                            FullName = "يوسف حسن",
                            IsAvailable = true,
                            Lat = 30.07,
                            Lng = 31.280000000000001,
                            PasswordHash = "123456",
                            Price = 70m,
                            Rating = 4.9000000000000004,
                            ReviewsCount = 211,
                            Role = "worker",
                            Specialty = "دهانات"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
